### ISSUE TITLE
CUDA 11 support?

### ISSUE THREAD

**Issue by yosun** [youngLBW/HRN#30]
```
/home/yc/anaconda3/envs/HRN/lib/python3.8/site-packages/h5py/__init__.py:46: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "demo.py", line 78, in <module>
    run_hrn(args)
  File "demo.py", line 15, in run_hrn
    reconstructor = Reconstructor(params)
  File "/home/yc/testing3dai/HRN/HRN/models/hrn.py", line 25, in __init__
    opt = TestOptions().parse(params)
  File "/home/yc/testing3dai/HRN/HRN/options/base_options.py", line 119, in parse
    opt = self.gather_options(params)
  File "/home/yc/testing3dai/HRN/HRN/options/base_options.py", line 68, in gather_options
    model_option_setter = models.get_option_setter(model_name)
  File "/home/yc/testing3dai/HRN/HRN/models/__init__.py", line 50, in get_option_setter
    model_class = find_model_using_name(model_name)
  File "/home/yc/testing3dai/HRN/HRN/models/__init__.py", line 33, in find_model_using_name
    modellib = importlib.import_module(model_filename)
  File "/home/yc/anaconda3/envs/HRN/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/yc/testing3dai/HRN/HRN/models/facerecon_model.py", line 7, in <module>
    from .losses import perceptual_loss, photo_loss, reg_loss, reflectance_loss, landmark_loss, TVLoss, TVLoss_std, contour_aware_loss
  File "/home/yc/testing3dai/HRN/HRN/models/losses.py", line 6, in <module>
    from pytorch3d.ops import (
  File "/home/yc/anaconda3/envs/HRN/lib/python3.8/site-packages/pytorch3d/ops/__init__.py", line 5, in <module>
    from .graph_conv import GraphConv
  File "/home/yc/anaconda3/envs/HRN/lib/python3.8/site-packages/pytorch3d/ops/graph_conv.py", line 8, in <module>
    from pytorch3d import _C
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory
```
`ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory`

**Comment by youngLBW** [comment]
Your pytorch3d may not be installed correctly. You can refer to https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md
