### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by misakamage** [youngLBW/HRN#54]
Traceback (most recent call last):
  File "/home/misaka/HRN/demo.py", line 78, in <module>
    run_hrn(args)
  File "/home/misaka/HRN/demo.py", line 26, in run_hrn
    output = reconstructor.predict(img, visualize=True, save_name=save_name, out_dir=out_dir)
  File "/home/misaka/HRN/models/hrn.py", line 238, in predict
    output = self.predict_base(img)
  File "/home/misaka/HRN/models/hrn.py", line 150, in predict_base
    im_tensor, lm_tensor, im_hd_tensor, lm_hd_tensor, mask = self.read_data(img, landmarks, self.lm3d_std, image_res=512, img_fat=fatbgr)
  File "/home/misaka/HRN/models/hrn.py", line 61, in read_data
    _, im_lr, lm_lr, _ = align_img(im, lm, lm3d_std)
  File "/home/misaka/HRN/util/preprocess.py", line 194, in align_img
    trans_params = np.array([w0, h0, s, t[0], t[1]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.
[1]-  Killed                  CUDA_VISIBLE_DEVICES=0 python demo.py --input_type single_view --input_root ./assets/examples/single_view_image --output_root ./assets/examples/single_view_image_results

How should I go about resolving this issue?

**Comment by youngLBW** [comment]
Hi, it should be caused by the wrong numpy version. You can try to install numpy<1.24.0. We will fix this bug soon.
